application: heartharcade
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /font
  static_dir: font
- url: /json
  static_dir: json
- url: /.*
  script: game.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest