application: heartharcade
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /font
  static_dir: font
- url: /json
  static_dir: json
- url: /pusher
  script: pusher.php
- url: /.*
  script: game.php